import { TechniqueData } from '@/types';

// All 48 techniques from the original HTML
export const techniques: TechniqueData[] = [
  { id: 1, name: 'Gratitude Journaling', description: "Write 3-5 specific things you're grateful for. Specificity produces strongest results.", details: "One of the most studied techniques. Generic entries like \"grateful for family\" produce weaker results than specific ones like \"colleague covered for me.\" Research shows once or twice a week beats rushed daily entries.", tags: ['Anxiety', 'Depression', 'Optimism'], prompts: ['What small thing happened today that you almost missed being grateful for?', 'What opportunity do you have right now that you take for granted?'], image: 'https://i.pinimg.com/736x/49/53/20/49532083572c937cf2c2746c4b5cfb12.jpg' },
  { id: 2, name: 'Morning Pages', description: 'Three pages of stream-of-consciousness writing every morning before anything else.', details: "Created by Julia Cameron. No rules — complain, daydream, worry, repeat yourself. The goal is to empty your mental inbox so what remains is clearer, calmer, more creative.", tags: ['Writers', 'Artists', 'Overthinkers'], prompts: ['Use A4 paper. Do it with morning coffee before checking phone. Don\'t reread for the first several weeks.'], image: 'https://i.pinimg.com/736x/49/53/20/49532083572c937cf2c2746c4b5cfb12.jpg' },
  { id: 3, name: 'Bullet Journaling', description: 'Rapid-logging system for tasks, notes, events, habit trackers — every journal unique.', details: 'Developed by Ryder Carroll. Bridges organization and self-reflection. Build monthly logs, weekly spreads, habit trackers, collection pages.', tags: ['Productivity', 'ADHD', 'Habit Building'], prompts: [] },
  { id: 4, name: 'Stream of Consciousness', description: "Write exactly what's in your mind — no editing, no pausing. The pen never stops.", details: "Pure unfiltered output. If you run out of thoughts, write \"I don't know what to say\" until something surfaces. Works especially when emotionally activated.", tags: ['Emotion Processing', 'Creative Blocks', 'Self-Discovery'], prompts: [] },
  { id: 5, name: 'Expressive Writing', description: 'Most scientifically backed — 15-20 min for 3-4 days about deepest feelings on a difficult experience.', details: "Developed by Dr. Pennebaker. Studies show fewer doctor visits, improved immunity, faster healing, reduced anxiety and PTSD.", tags: ['Trauma', 'Grief', 'PTSD'], prompts: ['Works best alongside professional support for severe trauma.'], image: 'https://i.pinimg.com/1200x/ae/02/ac/ae02ac95c816368594d3ef556ffbc451.jpg' },
  { id: 6, name: 'Dream Journaling', description: 'Record dreams immediately upon waking. Patterns reveal subconscious preoccupations.', details: 'Within five minutes most dreams fade — keep notebook by bed. Patterns emerge revealing preoccupations, fears, desires your waking mind may not acknowledge.', tags: ['Creatives', 'Subconscious', 'Nightmares'], prompts: [] },
  { id: 7, name: 'Shadow Work Journaling', description: 'Explore repressed, denied, or hidden parts of yourself. Goal is integration, not punishment.', details: 'Based on Carl Jung. Requires uncomfortable honesty — examine why certain people trigger strong reactions. Reports of greater self-compassion and healthier relationships.', tags: ['Deep Self-Discovery', 'Relationships', 'Limiting Beliefs'], prompts: ['What qualities in others bother you most? What does that reveal about you?'], image: 'https://i.pinimg.com/736x/49/53/20/49532083572c937cf2c2746c4b5cfb12.jpg' },
  { id: 8, name: 'Manifestation & Vision', description: 'Write about goals as though already achieved. 42% more likely to achieve written goals.', details: 'Rooted in goal-setting research. Create detailed descriptions of ideal life. Written goals engage your brain differently than unwritten ones.', tags: ['Goal Setting', 'Career', 'Self-Confidence'], prompts: [] },
  { id: 9, name: 'Reflective Journaling', description: 'Review experiences and draw insights. Converts raw experience into genuine understanding.', details: 'Ask: What did this teach me? How did I handle it? What would I do differently? Used extensively in education and professional settings.', tags: ['Professionals', 'Students', 'Life Transitions'], prompts: [] },
  { id: 10, name: 'The Five Whys', description: 'Ask "Why?" five times. By the 4th-5th, you arrive at core fears and unmet needs.', details: 'From manufacturing. First two produce surface answers. By fourth-fifth you often arrive at something not consciously acknowledged.', tags: ['Problem-Solving', 'Anxiety', 'Root Cause'], prompts: [] },
  { id: 11, name: 'Art Journaling', description: 'Combine writing with visual expression. No artistic skill needed.', details: 'Drawing, painting, collage, watercolor, stickers. Words optional. Expresses what words cannot capture. Most powerful pages are often the messiest.', tags: ['Visual Thinkers', 'Writing-Averse', 'Emotional Processing'], prompts: [] },
  { id: 12, name: 'Prompted Journaling', description: 'Respond to specific questions instead of facing a blank page.', details: 'From "What\'s on my mind?" to deeply specific exploratory prompts. Quality of prompt directly influences quality of insight.', tags: ['Beginners', 'Feeling Stuck', 'Specific Exploration'], prompts: [] },
  { id: 13, name: 'Unsent Letter Writing', description: "Write to someone you'll never send it to. Complete freedom to be honest.", details: "To someone who hurt you, someone you miss, your younger self, future self. Most emotionally powerful and underused technique.", tags: ['Grief', 'Anger', 'Forgiveness', 'Loss'], prompts: [] },
  { id: 14, name: 'Daily Review', description: '5-15 min end-of-day: one thing well, one challenge, one lesson, one intention.', details: 'From Benjamin Franklin to Oprah — compounding returns on minimal time. Becomes a detailed map of patterns, growth, and progress.', tags: ['Busy People', 'Goal Trackers', 'Sustainability'], prompts: [] },
  { id: 15, name: 'Nature Journaling', description: 'Record observations of the natural world. Close attention is mindfulness.', details: 'Birds, light, seasons, bark texture. May include sketches. Reduces anxiety and restores mental energy through focused observation.', tags: ['Stress Relief', 'Mindfulness', 'Screen Fatigue'], prompts: [] },
  { id: 16, name: 'Travel Journaling', description: "Preserves not what you saw but how you felt. Sensory details stay alive in writing.", details: 'The smell of a market, rain on a roof, light across ruins. Write at end of each day. Many incorporate mementos.', tags: ['Travelers', 'Memory', 'Self-Discovery'], prompts: ['What moment today would you want to remember in twenty years?', 'Describe this place through all five senses.'] },
  { id: 17, name: 'Food & Nutrition', description: 'Most research-backed behavioral change tool. Explore emotional relationship with eating.', details: 'Track what you eat and explore when you reach for food that isn\'t hunger. What moods trigger certain patterns?', tags: ['Health Goals', 'Mindful Eating', 'Recipes'], prompts: [] },
  { id: 18, name: 'Fitness & Workout', description: 'Track workouts, energy, recovery, mental state. Creates data to train intelligently.', details: 'Not just exercises but how your body felt, energy level, mental state. Patterns emerge about best conditions.', tags: ['Athletes', 'Fitness Goals', 'Injury Recovery'], prompts: [] },
  { id: 19, name: 'Financial', description: 'Most financial problems are psychology problems, not math problems.', details: 'Track money but also examine beliefs about spending, emotions driving decisions. A journal surfaces what no budgeting app can address.', tags: ['Debt Recovery', 'Saving', 'Money Psychology'], prompts: ['What was the first money lesson you learned as a child?', 'Write about your last impulse purchase — what emotion preceded it?'] },
  { id: 20, name: 'Relationship', description: "Understand your own role and patterns — not venting about others.", details: 'Focus on your reactions, needs, communication patterns. Often reveals the common thread is an unmet need you bring to each relationship.', tags: ['Communication', 'Breakup Healing', 'Attachment Patterns'], prompts: ['What do you need most that you have difficulty asking for?'] },
  { id: 21, name: 'Couples Journaling', description: 'Partners write to each other in a shared journal. Structured alternative to difficult talks.', details: 'Writing gives time to think, removes heat of confrontation, creates record of appreciation and intentions.', tags: ['Couples', 'Long-Distance', 'Difficult Conversations'], prompts: [] },
  { id: 22, name: 'Parenting & Family', description: "Captures first words, milestones, your own growth as a parent. A precious gift.", details: 'Not just for children\'s memories — reflective space for the parent. Some write directly to their child in second person.', tags: ['New Parents', 'Memory', 'Parental Healing'], prompts: [] },
  { id: 23, name: 'Pregnancy & Motherhood', description: 'Weekly entries on physical changes, emotions, fears, hopes, becoming a parent.', details: 'Pregnancy brings up identity questions, relationship reflections, values — all benefiting from reflective space.', tags: ['Pregnancy', 'Postpartum', 'Fertility'], prompts: [] },
  { id: 24, name: 'Legacy & Memory', description: "Written for those who come after — life story, values, lessons. An act of generosity.", details: 'The specific texture of a life disappears when undocumented. People who lost parents without documented memories become most committed legacy journalers.', tags: ['Family History', 'Grief', 'Life Arc'], prompts: [] },
  { id: 25, name: 'Recovery & Sobriety', description: 'Core tool in twelve-step frameworks. Track milestones, explore triggers.', details: 'Include tracking milestones, exploring triggers and cravings, processing underlying emotional pain, documenting gratitude.', tags: ['Addiction Recovery', 'Eating Disorders', 'Compulsive Behavior'], prompts: [] },
  { id: 26, name: 'Inner Child', description: 'Write to, from, or about your younger self. Access feelings your adult mind suppresses.', details: 'Write a letter to yourself at a specific age from your wiser self. Or write as your inner child in a spontaneous voice.', tags: ['Deep Healing', 'Childhood Trauma', 'Therapy Complement'], prompts: [] },
  { id: 27, name: 'Career & Professional', description: 'Reflect on goals, progress, challenges. Produces clarity no pros-and-cons list can.', details: 'Especially powerful during transitions. Many senior leaders journal to process decisions and examine leadership behaviors.', tags: ['Career Transition', 'Leadership', 'Workplace'], prompts: [] },
  { id: 28, name: 'Academic & Student', description: 'Writing about what you learned produces dramatically better retention.', details: 'Explain in your own words, connect to prior knowledge, note what confuses you. Used in medical, law, teacher training programs.', tags: ['Students', 'Professionals in Training', 'Retention'], prompts: [] },
  { id: 29, name: 'Entrepreneur & Business', description: 'Thinking partner, decision log, creative space, emotional outlet in one.', details: 'Captures ideas before they disappear, documents reasoning behind decisions, processes isolation and self-doubt.', tags: ['Founders', 'Freelancers', 'Side Hustlers'], prompts: [] },
  { id: 30, name: 'Project Journaling', description: 'Dedicated journal for one project — brainstorming, decisions, progress.', details: 'Writers develop characters, designers document concept evolution, scientists note hypotheses.', tags: ['Writers', 'Designers', 'Researchers', 'Builders'], prompts: [] },
  { id: 31, name: 'Prayer & Spiritual', description: "One of the oldest practices — written prayers, reflections, records of inner experience.", details: 'From Augustine to Thomas Merton. Not limited to any tradition. Creates space for meaning, purpose, and inner experience.', tags: ['Spiritual Practice', 'Faith Exploration', 'Purpose'], prompts: [] },
  { id: 32, name: 'Bible & Scripture', description: 'Writing in response to sacred texts transforms passive reading into active dialogue.', details: 'What the text clarifies, challenges, raises, and how it speaks to your current life. Extends to Quran, Torah, Bhagavad Gita.', tags: ['People of Faith', 'Deeper Engagement', 'Any Tradition'], prompts: [] },
  { id: 33, name: 'Stoic Journaling', description: 'Morning prep, evening review, negative visualization, dichotomy of control, memento mori.', details: "From Marcus Aurelius's Meditations — perhaps history's most famous journal. Builds philosophical muscle that strengthens under pressure.", tags: ['Stoic Philosophy', 'Anxiety', 'Leadership'], prompts: ['Write everything that bothered you today. For each: was it within your control?'] },
  { id: 34, name: 'Tarot Journaling', description: 'Uses card imagery as prompts for self-examination. Works with or without supernatural belief.', details: 'The 78-card deck is a symbolic vocabulary of human experience — archetypes of transformation, loss, joy, power, love.', tags: ['Creative Thinkers', 'Symbolic Exploration', 'Unusual Prompts'], prompts: [] },
  { id: 35, name: 'CBT Journaling', description: 'Identify negative thoughts, examine evidence, replace with balanced perspectives.', details: 'Central to CBT: trigger → automatic thought → emotion → evidence for → evidence against → balanced thought → revised emotion.', tags: ['Anxiety', 'Depression', 'Perfectionism'], prompts: ['Situation → Thought → Emotion (0-100%) → Evidence for → Against → Balanced → Revised emotion.'] },
  { id: 36, name: 'DBT Journaling', description: 'Supports mindfulness, distress tolerance, emotional regulation, interpersonal effectiveness.', details: 'Developed by Marsha Linehan. The diary card is essentially a structured daily journal.', tags: ['Emotional Sensitivity', 'BPD', 'Overwhelming Emotions'], prompts: [] },
  { id: 37, name: 'Healing Journal', description: 'Conscious healing process — for illness, chronic pain, trauma, grief, or life disruption.', details: 'Track symptoms and treatment, or tell your story at your own pace. Often incorporates gratitude, expressive writing, and letter techniques.', tags: ['Chronic Illness', 'Trauma Recovery', 'Grief'], prompts: [] },
  { id: 38, name: 'Mindfulness Journaling', description: "Focus on what's happening right now — body, senses, surroundings, current state.", details: 'Begin with body scan, then observe thoughts as weather passing through a sky. Writing slows you enough to notice.', tags: ['Being Present', 'Rumination', 'Meditation'], prompts: [] },
  { id: 39, name: 'Photo Journaling', description: 'Select images intentionally and write about their meaning. Camera as journaling tool.', details: 'Over time, a richly layered record of what your life looked like AND felt like. Simplified version: one meaningful photo per day with a sentence.', tags: ['Visual Thinkers', 'Photographers', 'Creative Mindfulness'], prompts: [] },
  { id: 40, name: 'Junk & Smash Journaling', description: 'Mixed-media with repurposed materials — intentionally imperfect, layered, handmade.', details: 'Old book pages, clippings, coffee-stained paper, fabric scraps. Tactile process is deeply relaxing and meditative.', tags: ['Tactile Learners', 'Crafts', 'Screen-Free'], prompts: [] },
  { id: 41, name: 'Mind Mapping', description: 'Visual branching diagrams. Non-linear connections sequential writing suppresses.', details: 'Core concept at center, branches for themes, sub-branches for associations. Powerful warm-up before longer entries.', tags: ['Visual Thinkers', 'Complex Decisions', 'Brainstorming'], prompts: [] },
  { id: 42, name: 'One Line a Day', description: 'Exactly one sentence per day. Most minimal viable practice.', details: "Captures day's essence without time or inspiration. Over months, cumulative record becomes surprisingly rich.", tags: ['Absolute Beginners', 'Very Little Time', 'Habit Building'], prompts: [] },
  { id: 43, name: 'Two-Column', description: 'Opposing perspectives side by side. Seeing both in parallel reduces emotional reactivity.', details: 'Fear vs hope, rational vs gut, positive vs negative. When both sides laid out in parallel, brain evaluates with less emotional reactivity.', tags: ['Decision-Making', 'Conflict', 'Anxiety'], prompts: [] },
  { id: 44, name: 'List Journaling', description: 'Replace prose with curated lists. Faster, more honest, highly versatile.', details: 'Ten things of joy, five fears, twenty goals. Lists are faster, easier to reread, often more honest.', tags: ['Prose Difficulty', 'Low Pressure', 'Quick Clarity'], prompts: [] },
  { id: 45, name: 'Reading Journal / Commonplace', description: "Personal anthology of wisdom from everything you read. From Marcus Aurelius to da Vinci.", details: 'Copy meaningful passages by hand — best way to internalize. Creates personalized intellectual library.', tags: ['Readers', 'Writers', 'Students', 'Thinkers'], prompts: [] },
  { id: 46, name: 'Idea & Creativity', description: "Capture, develop, organize creative ideas. Ideas not written within minutes are gone forever.", details: "Don't just store — return, add, cross-reference, challenge. Many prolific creators credit this discipline with significant output.", tags: ['Creative Fields', 'Entrepreneurs', 'Inventors'], prompts: [] },
  { id: 47, name: 'Garden & Seasonal', description: 'Track garden life across seasons. Practical record plus reflective nature connection.', details: 'What was planted, conditions, what grew, wildlife. Same walk at different times over years creates remarkable record.', tags: ['Gardeners', 'Naturalists', 'Seasonal Rhythms'], prompts: [] },
  { id: 48, name: 'Medical & Health', description: 'Track symptoms, medications, appointments. Transforms vague impressions into specific records.', details: 'Doctors report patients with detailed journals provide far more useful information. Also serves emotional function.', tags: ['Chronic Conditions', 'New Diagnosis', 'Recovery', 'Healthcare'], prompts: [] },
];

// Color mapping for technique categories
export const categoryColors: Record<string, { bg: string; border: string; text: string; accent: string }> = {
  v: { bg: 'var(--cvb)', border: 'var(--cvd)', text: 'var(--cv)', accent: 'var(--cv)' },
  e: { bg: 'var(--ceb)', border: 'var(--ced)', text: 'var(--ce)', accent: 'var(--ce)' },
  a: { bg: 'var(--cab)', border: 'var(--cad)', text: 'var(--ca)', accent: 'var(--ca)' },
  rose: { bg: 'var(--crb)', border: 'var(--crd)', text: 'var(--cr)', accent: 'var(--cr)' },
  sky: { bg: 'var(--csb)', border: 'var(--csd)', text: 'var(--cs)', accent: 'var(--cs)' },
  pur: { bg: 'var(--cpb)', border: 'var(--cpd)', text: 'var(--cp)', accent: 'var(--cp)' },
  red: { bg: 'var(--creb)', border: 'var(--cred)', text: 'var(--cre)', accent: 'var(--cre)' },
  teal: { bg: 'var(--ctb)', border: 'var(--ctd)', text: 'var(--ct)', accent: 'var(--ct)' },
  org: { bg: 'var(--cob)', border: 'var(--cod)', text: 'var(--co)', accent: 'var(--co)' },
};

export function getTechniqueCategory(id: number): string {
  if (id <= 7) return 'v';
  if (id <= 14) return 'e';
  if (id <= 21) return 'a';
  if (id <= 26) return 'rose';
  if (id <= 30) return 'sky';
  if (id <= 34) return 'pur';
  if (id <= 38) return 'red';
  if (id <= 44) return 'teal';
  return 'org';
}

export const categories = [
  { id: 1, title: 'Self-Reflection & Emotional Processing', desc: 'The most well-researched techniques for understanding your inner world.', range: '1–7', color: 'v' },
  { id: 2, title: 'Growth & Goal-Oriented', desc: 'Accelerate learning, achieve goals, develop as a person.', range: '8–14', color: 'e' },
  { id: 3, title: 'Lifestyle & Specialized', desc: 'Journaling applied to nature, travel, food, fitness, money, relationships.', range: '15–21', color: 'a' },
  { id: 4, title: 'Life Stage & Identity', desc: 'Parenting, pregnancy, legacy, recovery, inner child work.', range: '22–26', color: 'rose' },
  { id: 5, title: 'Professional & Academic', desc: 'Career, learning, entrepreneurship, project management.', range: '27–30', color: 'sky' },
  { id: 6, title: 'Spiritual & Philosophical', desc: 'Meaning, purpose, faith, and the inner life through writing.', range: '31–34', color: 'pur' },
  { id: 7, title: 'Therapeutic & Healing', desc: 'CBT, DBT, healing journals, mindfulness-based approaches.', range: '35–38', color: 'red' },
  { id: 8, title: 'Creative & Experimental', desc: 'Photo, junk journals, mind maps, lists, mixed-media approaches.', range: '39–44', color: 'teal' },
  { id: 9, title: 'Hobby & Special Interest', desc: 'Reading, ideas, gardens, health tracking — practices you already love.', range: '45–48', color: 'org' },
];